title: Kyle Hardy
logo: Headshot.JPG
description: 
  - 2024 statistics graduate
  - Contact Info:
  - Phone Number: 504-439-1787
  - Email: Kylehardy3118@gmail.com
show_downloads: yes
theme: jekyll-theme-minimal
