title: Kyle Hardy
logo: Headshot.JPG
description: 2024 statistics graduate
description: Contact Info:
description: Phone Number: 504-439-1787
description: Email: Kylehardy3118@gmail.com
show_downloads: yes
theme: jekyll-theme-minimal
